name: it_book_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  dio: ^4.0.4
  connectivity_plus: ^2.2.1
  bot_toast: ^4.0.1
  dartz: ^0.10.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


#  assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: GothamRounded
      fonts:
        - asset: assets/fonts/GothamRounded-Regular.ttf
          weight: 200
        - asset: assets/fonts/GothamRounded-Light.ttf
        - asset: assets/fonts/GothamRounded-Bold.ttf
          weight: 700
